defaults:
  - identify_associations_bayes

multiprocess: True

batch_size: 250

num_refits: 2

target_dataset: iso_tpm_100 # Dataset to perturb 
target_value: maximum # We perturb in all samples for the maximum value of that feature across all samples
save_refits: True

model:
  num_hidden:
    - 150 
  num_latent: 10 
  beta: 0.001
  dropout: .1 
  cuda: false

training_loop:
  lr: 1e-4
  num_epochs: 20